import 'package:flutter/material.dart';
import 'package:valarpay/core/utils/color_utils.dart';

class ShareableTransactionReceiptDetail {
  final String label;
  final String value;
  final bool? isSuccessful;

  ShareableTransactionReceiptDetail(
      {required this.label, required this.value, this.isSuccessful});
}

class ShareableTransactionReceipt extends StatelessWidget {
  final List<ShareableTransactionReceiptDetail> transactionDetailList;
  final String date;

  const ShareableTransactionReceipt(
      {super.key, required this.transactionDetailList, required this.date});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: Color(0XFFFFEEE3),
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black12,
            blurRadius: 8,
            spreadRadius: 2,
          )
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Header
          Container(
            padding: EdgeInsets.all(16),
            width: double.infinity,
            color: appTheme.primaryColor,
            child: Column(
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Image.asset('assets/images/logo.png', height: 24),
                    const Text(
                      "Beyond Banking",
                      style: TextStyle(fontWeight: FontWeight.w600),
                    ),
                  ],
                ),
                const SizedBox(height: 8),
                const Text(
                  "Transaction Receipt",
                  style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                      color: Colors.white),
                ),
                Text(
                  "Generated by ValarPay on $date",
                  style: const TextStyle(fontSize: 12, color: Colors.white),
                ),
              ],
            ),
          ),

          const SizedBox(height: 16),
          Container(
            padding: EdgeInsets.all(16),
            child: Column(
              children: [_buildDetailsCard(context, transactionDetailList)],
            ),
          ),

          const SizedBox(height: 16),
          const Text(
            "Thank you for banking with ValarPay.\nFor support, contact us at support@valarpay.com",
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 11, color: Colors.grey),
          ),
          const SizedBox(height: 16),
        ],
      ),
    );
  }

  Widget _buildDetailsCard(
      BuildContext context, List<ShareableTransactionReceiptDetail> details) {
    return Column(
      children: details.asMap().entries.map((entry) {
        final index = entry.key;
        final detail = entry.value;
        final isLast = index == details.length - 1;

        return Column(
          children: [
            _buildDetailRow(context, detail),
            if (!isLast) const SizedBox(height: 12),
          ],
        );
      }).toList(),
    );
  }

  Widget _buildDetailRow(
      BuildContext context, ShareableTransactionReceiptDetail detail) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(detail.label,
              style: const TextStyle(fontSize: 13, color: Colors.grey)),
          Flexible(
            child: Text(
              detail.value,
              textAlign: TextAlign.end,
              style: TextStyle(
                fontSize: 13,
                fontWeight: FontWeight.w500,
                color: detail.label == 'Status'
                    ? detail.isSuccessful != null && detail.isSuccessful == true
                        ? Colors.green
                        : Colors.red
                    : Colors.black,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
